apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: p2-baseline-require-common-labels
  labels:
    app.kubernetes.io/part-of: k8s-platform-lab
spec:
  admission: true
  background: true
  emitWarning: false
  validationFailureAction: Audit
  rules:
    - name: require-app-label-on-workloads
      skipBackgroundRequests: true
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - DaemonSet
                - Job
              namespaces:
                - apps
      validate:
        allowExistingViolations: true
        message: Workloads in apps namespace should have app.kubernetes.io/name label.
        pattern:
          metadata:
            labels:
              app.kubernetes.io/name: "?*"
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: p2-baseline-disallow-privileged-apps
  labels:
    app.kubernetes.io/part-of: k8s-platform-lab
spec:
  admission: true
  background: true
  emitWarning: false
  validationFailureAction: Audit
  rules:
    - name: disallow-privileged-containers-in-apps
      skipBackgroundRequests: true
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - apps
      validate:
        allowExistingViolations: true
        message: Application pods should not run privileged containers.
        foreach:
          - list: request.object.spec.containers[]
            deny:
              conditions:
                any:
                  - key: "{{ element.securityContext.privileged || `false` }}"
                    operator: Equals
                    value: true
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: p2-baseline-require-resource-requests-apps
  labels:
    app.kubernetes.io/part-of: k8s-platform-lab
spec:
  admission: true
  background: true
  emitWarning: false
  validationFailureAction: Audit
  rules:
    - name: require-cpu-memory-requests
      skipBackgroundRequests: true
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - apps
      validate:
        allowExistingViolations: true
        message: Application pods should define CPU and memory requests.
        foreach:
          - list: request.object.spec.containers[]
            pattern:
              resources:
                requests:
                  cpu: "?*"
                  memory: "?*"
