apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: p2-kube-prometheus-stack:/Service:monitoring/kube-prometheus-stack-prometheus
    creationTimestamp: "2026-07-11T17:15:40Z"
    labels:
      app: kube-prometheus-stack-prometheus
      app.kubernetes.io/instance: kube-prometheus-stack
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: kube-prometheus-stack
      app.kubernetes.io/version: 87.15.1
      chart: kube-prometheus-stack-87.15.1
      heritage: Helm
      release: kube-prometheus-stack
      self-monitor: "true"
    name: kube-prometheus-stack-prometheus
    namespace: monitoring
    resourceVersion: "912015"
    uid: 8695a4c1-73ae-49db-a1a3-9a1b8b1b901f
  spec:
    clusterIP: 10.43.27.218
    clusterIPs:
    - 10.43.27.218
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http-web
      port: 9090
      protocol: TCP
      targetPort: 9090
    - appProtocol: http
      name: reloader-web
      port: 8080
      protocol: TCP
      targetPort: reloader-web
    selector:
      app.kubernetes.io/name: prometheus
      operator.prometheus.io/name: kube-prometheus-stack-prometheus
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: p2-kube-prometheus-stack:/Service:monitoring/kube-prometheus-stack-grafana
    creationTimestamp: "2026-07-11T17:15:40Z"
    labels:
      app.kubernetes.io/instance: kube-prometheus-stack
      app.kubernetes.io/name: grafana
      app.kubernetes.io/version: 13.1.0
      helm.sh/chart: grafana-12.7.2
    name: kube-prometheus-stack-grafana
    namespace: monitoring
    resourceVersion: "912032"
    uid: 418474e7-e04f-469a-b209-c56800bb15a5
  spec:
    clusterIP: 10.43.108.153
    clusterIPs:
    - 10.43.108.153
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http-web
      port: 80
      protocol: TCP
      targetPort: grafana
    selector:
      app.kubernetes.io/instance: kube-prometheus-stack
      app.kubernetes.io/name: grafana
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: p2-kube-prometheus-stack:/Service:monitoring/kube-prometheus-stack-alertmanager
    creationTimestamp: "2026-07-11T17:15:40Z"
    labels:
      app: kube-prometheus-stack-alertmanager
      app.kubernetes.io/instance: kube-prometheus-stack
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: kube-prometheus-stack
      app.kubernetes.io/version: 87.15.1
      chart: kube-prometheus-stack-87.15.1
      heritage: Helm
      release: kube-prometheus-stack
      self-monitor: "true"
    name: kube-prometheus-stack-alertmanager
    namespace: monitoring
    resourceVersion: "912017"
    uid: 88b8e08d-f86d-4ce2-80a3-b1682688580b
  spec:
    clusterIP: 10.43.248.31
    clusterIPs:
    - 10.43.248.31
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http-web
      port: 9093
      protocol: TCP
      targetPort: 9093
    - appProtocol: http
      name: reloader-web
      port: 8080
      protocol: TCP
      targetPort: reloader-web
    selector:
      alertmanager: kube-prometheus-stack-alertmanager
      app.kubernetes.io/name: alertmanager
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
