apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: p2-argocd-crds
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: k8s-platform-lab
spec:
  project: default
  source:
    repoURL: https://github.com/hoangdonguit/k8s-platform-lab.git
    targetRevision: main
    path: clusters/p2/platform/argocd-crds
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
