apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: p2-kyverno
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: k8s-platform-lab
spec:
  project: default
  source:
    repoURL: https://github.com/hoangdonguit/k8s-platform-lab.git
    targetRevision: main
    path: clusters/p2/platform/kyverno
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
