fullnameOverride: kube-prometheus-stack

crds:
  enabled: true

defaultRules:
  create: true

alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1
    retention: 24h
    storage: {}

grafana:
  enabled: true
  defaultDashboardsEnabled: true
  adminPassword: admin
  service:
    type: ClusterIP
  ingress:
    enabled: false
  persistence:
    enabled: false

prometheus:
  enabled: true
  prometheusSpec:
    replicas: 1
    retention: 24h
    retentionSize: 4GB
    storageSpec: {}
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 2Gi
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false

prometheusOperator:
  enabled: true
  admissionWebhooks:
    enabled: true
    patch:
      enabled: true

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

kubelet:
  enabled: true

kubeApiServer:
  enabled: true

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false

coreDns:
  enabled: true

kubeEtcd:
  enabled: false
